package br.unibh.sdm.backend_cripto.entidades;

import java.math.BigDecimal;
import java.util.Date;
import java.util.Objects;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Cliente")
public class Cliente {

	public Cliente(String nome, String endereco, String email, String sexo, String estadoCivil, Date dtNascimento,
			String cPF, String rG, BigDecimal renda) {
		super();
		this.nome = nome;
		this.endereco = endereco;
		this.email = email;
		this.sexo = sexo;
		this.estadoCivil = estadoCivil;
		this.dtNascimento = dtNascimento;
		CPF = cPF;
		RG = rG;
		this.renda = renda;
	}


	private String id;
	private String nome;
	private String endereco;
	private String email;
	private String sexo;
	private String estadoCivil;
	private Date dtNascimento;
	private String CPF;
	private String RG;
	private BigDecimal renda;
	
	
	
	
	public Cliente() {
		super();
	}
	
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	@DynamoDBAttribute
	public String getNome() {
		return nome;
	}
	
	public void setNome(String nome) {
		this.nome = nome;
	}
	@DynamoDBAttribute
	public String getEndereco() {
		return endereco;
	}
	public void setEndereco(String endereco) {
		this.endereco = endereco;
	}
	@DynamoDBAttribute
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	@DynamoDBAttribute
	public String getSexo() {
		return sexo;
	}
	
	public void setSexo(String sexo) {
		this.sexo = sexo;
	}
	@DynamoDBAttribute
	public String getEstadoCivil() {
		return estadoCivil;
	}
	public void setEstadoCivil(String estadoCivil) {
		this.estadoCivil = estadoCivil;
	}
	@DynamoDBAttribute
	public Date getDtNascimento() {
		return dtNascimento;
	}
	public void setDtNascimento(Date dtNascimento) {
		this.dtNascimento = dtNascimento;
	}
	@DynamoDBAttribute
	public String getCPF() {
		return CPF;
	}
	public void setCPF(String cPF) {
		CPF = cPF;
	}
	@DynamoDBAttribute
	public String getRG() {
		return RG;
	}
	public void setRG(String rG) {
		RG = rG;
	}
	@DynamoDBAttribute
	public BigDecimal getRenda() {
		return renda;
	}
	public void setRenda(BigDecimal renda) {
		this.renda = renda;
	}


	@Override
	public String toString() {
		return "cliente [id=" + id + ", nome=" + nome + ", endereco=" + endereco + ", email=" + email + ", sexo=" + sexo
				+ ", estadoCivil=" + estadoCivil + ", dtNascimento=" + dtNascimento + ", CPF=" + CPF + ", RG=" + RG
				+ ", renda=" + renda + "]";
	}


	@Override
	public int hashCode() {
		return Objects.hash(CPF, RG, dtNascimento, email, endereco, estadoCivil, id, nome, renda, sexo);
	}


	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Cliente other = (Cliente) obj;
		return Objects.equals(CPF, other.CPF) && Objects.equals(RG, other.RG)
				&& Objects.equals(dtNascimento, other.dtNascimento) && Objects.equals(email, other.email)
				&& Objects.equals(endereco, other.endereco) && Objects.equals(estadoCivil, other.estadoCivil)
				&& Objects.equals(id, other.id) && Objects.equals(nome, other.nome)
				&& Objects.equals(renda, other.renda) && Objects.equals(sexo, other.sexo);
	}

	
	
	


		
}
